//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GiftServer.Properties.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notpmah678.
        /// </summary>
        internal static string emailPassword {
            get {
                return ResourceManager.GetString("emailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .png.
        /// </summary>
        internal static string ImageFormat {
            get {
                return ResourceManager.GetString("ImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * bootstrap-star-rating v4.0.2
        /// * http://plugins.krajee.com/star-rating
        /// *
        /// * Author: Kartik Visweswaran
        /// * Copyright: 2013 - 2017, Kartik Visweswaran, Krajee.com
        /// *
        /// * Licensed under the BSD 3-Clause
        /// * https://github.com/kartik-v/bootstrap-star-rating/blob/master/LICENSE.md
        /// */.rating-loading{width:25px;height:25px;font-size:0;color:#fff;background:url(../img/loading.gif) top left no-repeat;border:none}.rating-container .rating-stars{position:relative;cursor:pointer;vertical-align:middle;dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string starCSS {
            get {
                return ResourceManager.GetString("starCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * bootstrap-star-rating v4.0.2
        /// * http://plugins.krajee.com/star-rating
        /// *
        /// * Author: Kartik Visweswaran
        /// * Copyright: 2013 - 2017, Kartik Visweswaran, Krajee.com
        /// *
        /// * Licensed under the BSD 3-Clause
        /// * https://github.com/kartik-v/bootstrap-star-rating/blob/master/LICENSE.md
        /// */!function(e){&quot;use strict&quot;;&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],e):&quot;object&quot;==typeof module&amp;&amp;module.exports?module.exports=e(require(&quot;jquery&quot;)):e(window.jQuery)}(function(e){&quot;use strict&quot;;e.fn.ratingLoc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string starJS {
            get {
                return ResourceManager.GetString("starJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.thegifthub.org.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
    }
}
