//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GiftServer.Properties.HtmlTemplates", typeof(HtmlTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;My Dashboard&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./resources/CSS/dashboard.css&quot; /&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;./resources/scripts/dashboard.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;container-fluid&quot;&gt;
        ///        &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-md-3&quot;&gt;
        ///                &lt;!-- Feed --&gt;
        ///                &lt;div id=&quot;feedPanel&quot; class=&quot;panel panel-success&quot;&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en-us&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css&quot;&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;My Gift List&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./resources/CSS/list.css&quot; /&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;./resources/scripts/list.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;hidden&quot; id=&quot;thisUserId&quot; data-user-id=&quot;&quot;&gt;&lt;/div&gt;
        ///    &lt;div class=&quot;container-fluid&quot;&gt;
        ///        &lt;div id=&quot;deleteGiftWarning&quot; class=&quot;modal fade panel-danger&quot; role=&quot;dialog&quot;&gt;
        ///            &lt;div class=&quot;mod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;https://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;The Gift Hub is a place where you can list your gifts and reserve the gifts of others. Sign up today to start gifting!&quot; /&gt;
        ///    &lt;meta name=&quot;google-signin-client_id&quot; content=&quot;173734539372-5sgc5qa2gdt8f51e9o0c9a7463s3a9g4.apps.googleusercontent.com&quot;&gt;
        ///    &lt;script src=&quot;https://apis.google.com/js/platform.js?onload=renderGoogleLogin&quot; async defer&gt;&lt;/script&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./reso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;resources/scripts/navigationBar.js&quot;&gt;&lt;/script&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;resources/CSS/navigationBar.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;nav id=&quot;navBar&quot; class=&quot;navbar navbar-inverse navbar-fixed-top&quot;&gt;
        ///        &lt;div class=&quot;container-fluid&quot;&gt;
        ///            &lt;div class=&quot;navbar-header&quot;&gt;
        ///                &lt;button type=&quot;button&quot; class=&quot;navbar-toggle&quot; data-toggle=&quot;collapse&quot; data-target=&quot;#globalNav&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string navigationBar {
            get {
                return ResourceManager.GetString("navigationBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en-us&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Reset Password for The Gift Hub&lt;/title&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;resources/scripts/passwordReset.js&quot;&gt;&lt;/script&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;resources/CSS/passwordReset.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;container-fluid&quot;&gt;
        ///        &lt;div class=&quot;text-center&quot;&gt;
        ///            &lt;div class=&quot;row&quot;&gt;
        ///                &lt;div class=&quot;col-xs-12&quot;&gt;
        ///                    &lt;h1&gt;Reset Yo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string passwordReset {
            get {
                return ResourceManager.GetString("passwordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;userFound&quot;&gt;
        ///        &lt;h1&gt;Hey There&lt;/h1&gt;
        ///        &lt;p&gt;
        ///            Looks like you need to reset your password at The Gift Hub. To do so, just click &lt;a id=&quot;passwordReset&quot; href=&quot;&quot;&gt;here&lt;/a&gt;.
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///            If the link doesn&apos;t work, copy this into the browser of your choice: &lt;a id=&quot;resetURL&quot; href=&quot;&quot;&gt;&lt;/a&gt;
        ///        &lt;/p&gt;
        ///        &lt;br /&gt;
        ///        &lt;p&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string passwordResetEmail {
            get {
                return ResourceManager.GetString("passwordResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Hi There.&lt;/h1&gt;
        ///    &lt;h2&gt;Looks like you reset your password.&lt;/h2&gt;
        ///    &lt;div id=&quot;userName&quot;&gt;&lt;/div&gt;
        ///    &lt;br /&gt;
        ///    &lt;p&gt;&amp;nbsp;Looks like you reset your password. If you initiated this, then you&apos;re good to go! Otherwise, please reply to this email and we&apos;ll work all this out.&lt;/p&gt;
        ///    &lt;p&gt;
        ///        Best Regards,
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        The GiftHub Team
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string passwordResetNotification {
            get {
                return ResourceManager.GetString("passwordResetNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;The Gift Hub Privacy Policy&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;p&gt;This Privacy Policy governs the manner in which The Gift Hub collects, uses, maintains and discloses information collected from users (each, a &quot;User&quot;) of the https://www.thegifthub.org/ website (&quot;Site&quot;).&lt;/p&gt;
        ///
        ///    &lt;h3&gt;Personal identification information&lt;/h3&gt;
        ///    &lt;p&gt;We may collect personal identification information from Users in a variety of w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string privacyPolicy {
            get {
                return ResourceManager.GetString("privacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;google-signin-client_id&quot; content=&quot;173734539372-5sgc5qa2gdt8f51e9o0c9a7463s3a9g4.apps.googleusercontent.com&quot;&gt;
        ///    &lt;title&gt;My Profile&lt;/title&gt;
        ///    &lt;script src=&quot;https://apis.google.com/js/platform.js?onload=renderGoogleLogin&quot; async defer&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;./resources/scripts/profile.js&quot;&gt;&lt;/script&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./resources/CSS/profile.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title id=&quot;title&quot;&gt;&lt;/title&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;./resources/scripts/publicList.js&quot;&gt;&lt;/script&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./resources/CSS/publicList.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;!-- Format: id, name, class, type, placeholder, tooltip--&gt;
        ///    &lt;div class=&quot;hidden&quot; id=&quot;thisUserId&quot; data-user-id=&quot;&quot;&gt;&lt;/div&gt;
        ///    &lt;div class=&quot;container-fluid&quot;&gt;
        ///        &lt;div id=&quot;reserveGift&quot; class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string publicList {
            get {
                return ResourceManager.GetString("publicList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;My Profile&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./resources/CSS/publicProfile.css&quot; /&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;./resources/scripts/publicProfile.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;container-fluid&quot;&gt;
        ///        &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-4 text-center&quot;&gt;
        ///                &lt;!-- User Image --&gt;
        ///                &lt;img id=&quot;userImage&quot; class=&quot;img- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string publicProfile {
            get {
                return ResourceManager.GetString("publicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/resources/CSS/termsOfService.css&quot; /&gt;
        ///    &lt;title&gt;The Gift Hub Terms of Service&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;The Gift Hub Terms of Service&lt;/h2&gt;
        ///    &lt;h3&gt;1. Terms&lt;/h3&gt;
        ///    &lt;p&gt;By accessing the website at &lt;a href=&quot;https://www.thegifthub.org&quot;&gt;https://www.thegifthub.org&lt;/a&gt;, you are agreeing to be bound by these terms of service, all applicable laws and regulations,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string termsOfService {
            get {
                return ResourceManager.GetString("termsOfService", resourceCulture);
            }
        }
    }
}
